import assert from "node:assert/strict";
import fs from "node:fs";

const itemSheet = fs.readFileSync(new URL("../templates/item/item-sheet.hbs", import.meta.url), "utf8");
const physicalPart = fs.readFileSync(new URL("../templates/item/parts/physical.hbs", import.meta.url), "utf8");
const sheetSource = fs.readFileSync(new URL("../modules/sheets/item-sheet.mjs", import.meta.url), "utf8");
const chargenSource = fs.readFileSync(new URL("../modules/apps/character-creation.mjs", import.meta.url), "utf8");
const selectionBrowserSource = fs.readFileSync(new URL("../modules/apps/chargen/selection-browser.mjs", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("../css/veilrunner.css", import.meta.url), "utf8");

assert.match(itemSheet, /data-action="setItemTab" data-tab="details"/);
assert.match(itemSheet, /data-action="setItemTab" data-tab="description"/);
assert.match(itemSheet, /<prose-mirror class="vr-item-description-editor" name="\{\{descriptionPath\}\}"/);
assert.match(itemSheet, /<prose-mirror class="vr-item-description-editor" name="system\.description\.gm"/);
assert.doesNotMatch(itemSheet, /\{\{editor\b/, "the non-interactive editor helper should not return");
assert.doesNotMatch(physicalPart, /\{\{editor\b/, "physical descriptions should use the shared Description tab");
assert.match(sheetSource, /context\.descriptionPath = context\.isPhysical \? "system\.description\.value" : "system\.description"/);
assert.match(sheetSource, /TextEditor\.enrichHTML\(context\.descriptionValue/);
assert.match(sheetSource, /\["details", "description"\]\.includes\(tab\)/);
assert.match(sheetSource, /context\.personaText = normalizeTextList\(context\.system\.persona\)\.join\(", "\)/);
assert.match(itemSheet, /name="system\.persona" value="\{\{personaText\}\}"/);
assert.match(itemSheet, /data-action="setCharacterOptionArtwork"/);
assert.match(sheetSource, /new FilePickerClass\(\{\s*type: "image",\s*current: this\.item\.img,/);
assert.match(sheetSource, /this\.item\.update\(\{ img: path \}\)/);
assert.match(chargenSource, /getIndex\(\{ fields: \["system\.persona", "system\.description", "folder"\] \}\)/);
assert.match(chargenSource, /description: foundry\.utils\.getProperty\(entry, "system\.description"\)/);
assert.match(chargenSource, /img: entry\.img \?\? ""/);
assert.match(chargenSource, /#loadPathReferenceOptions\(\)/);
for (const packId of ["Veilrunner.archetypes", "Veilrunner.professions", "Veilrunner.disciplines"]) assert.ok(chargenSource.includes(packId), `chargen loads ${packId}`);
assert.match(chargenSource, /this\.pathReferenceOptions = \{ archetype: \[\], profession: \[\], discipline: \[\] \}/);
assert.match(chargenSource, /img: pathImage\("discipline", discipline, record\)/);
assert.match(chargenSource, /const stageReference = mode === "all"[\s\S]*?Browse All Disciplines[\s\S]*?: this\.#professionReference\(stage\)/, "All mode uses neutral Path guidance instead of the previously selected Discipline");
assert.match(chargenSource, /current\.key === "level" \? `<aside class="vr-cc-info vr-cc-details-pane vr-cc-reference-details vr-cc-level-details">/, "Level of Play uses the Identity inspector shell");
assert.match(chargenSource, /vr-cc-level-inspector-art[\s\S]*?vr-cc-inspector-about-tab[\s\S]*?vr-cc-inspector-content vr-cc-level-info/, "Level of Play follows the Identity inspector composition");
assert.match(chargenSource, /else if \(!this\.pathTransitioning && path !== "discipline"\)/, "Discipline card selection does not replay the Path section transition");
assert.match(chargenSource, /vr-cc-reference-card vr-cc-selection-card vr-cc-full-art-choice-card vr-cc-identity-choice-card/);
assert.doesNotMatch(chargenSource, /vr-cc-choice-name[^\n]*<\/strong><em>\$\{escape\(category\.name\)\}<\/em>/);
assert.match(chargenSource, /vr-cc-reference-card vr-cc-full-art-choice-card vr-cc-level-full-art-card/);
assert.match(chargenSource, /vr-cc-level-custom vr-cc-full-art-choice-card vr-cc-level-full-art-card/);
assert.doesNotMatch(selectionBrowserSource, /vr-cc-major-choice-card/);
assert.match(selectionBrowserSource, /vr-cc-selection-card vr-cc-full-art-choice-card vr-cc-path-choice-card/);
assert.match(selectionBrowserSource, /option\.img \? `<img src=/, "Path cards render authored artwork when available");
assert.match(selectionBrowserSource, /vr-cc-choice-name vr-cc-path-choice-name/, "Path labels use the shared bottom overlay");
assert.match(css, /vr-cc-reference-cards-species[\s\S]*?vr-cc-choice-image img[\s\S]*?object-fit: cover;/);
assert.match(css, /vr-cc-reference-cards-origin,.vr-cc-reference-cards-background[\s\S]*?vr-cc-choice-image img[\s\S]*?object-fit: cover;/);
assert.match(css, /vr-cc-full-art-choice-card \.vr-cc-selection-art[\s\S]*?position: absolute;[\s\S]*?inset: 0;[\s\S]*?margin: 0;/);
assert.match(css, /vr-cc-full-art-choice-card > \.vr-cc-choice-name[\s\S]*?position: absolute;[\s\S]*?bottom: 0;[\s\S]*?background: rgba\(3, 9, 15, \.62\);/);
assert.match(css, /vr-cc-level-full-art-card > \.vr-cc-level-choice-name/);
assert.match(css, /button\.vr-cc-level-full-art-card:hover,[\s\S]*?button\.vr-cc-level-full-art-card:focus-visible[\s\S]*?outline: 0 !important;/);
assert.match(css, /vr-cc-selection-browser \.vr-cc-selection-card > \.vr-cc-selection-art[\s\S]*?justify-self: stretch;[\s\S]*?align-self: stretch;/);
assert.match(css, /vr-cc-path-choice-card > \.vr-cc-path-choice-name[\s\S]*?display: grid;/);

console.log("shared Item details editor and chargen description checks passed");
